### ISSUE TITLE
Onboarding Guide Request

### ISSUE THREAD

**Issue by Henry-WattTime** [lf-energy/lfess-resources#3]
### Please describe the resource requested

A onboarding guide that explains the organizational structure, how to join, the meaning of different membership levels, and an overview of how you can be involved would be exceptionally helpful. 

### Why would you like it added

So that folks joining the CDSC project know what is going on and how they can be involved. What is the legal structure and why was it chosen? Is it even called the CDSC or is it now LFESS? 

### How soon do you need this added

As new people come on board and want to contribute.

### Additional context

There's been so much change in the organizational structure over different iterations that I've lost track of the current organizational structure.

**Comment by jmertic** [comment]
Thanks @Henry-WattTime - can you review the doc added in #4 and let me know if that addresses the asks?

**Comment by Henry-WattTime** [comment]
This looks great, I added a few minor comments.
